language: java
before_install:
- git clone https://github.com/Enrico204/JMessageNetLib _lib && pushd _lib && mvn
  install && popd
before_deploy:
- export RELEASE_PKG_FILE=$(ls target/JMessageNetSMSSender*jar-with-dependencies.jar)
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${RELEASE_PKG_FILE}"
  on:
    tags: true
  api-key:
    secure: vCBE+vHIhLDrwpqvDxABpo4zI/iApF2auVkPcFHcBaN2V3Uuz1PaMvCA9d67+9rK1zzJCNw8zYLUmq4Q/hnhKbpXtmfGsEnprKNDM3Tvgy+xWmBlNmmyPtCMCXObXXjL/yFiKKbuRLZ+OAXdsYT1cilC2wopOFmp2iyBPI5S862Bq5UNkvHy/MzR/ngqwvxMv0jl2+Q/87SF71HVW44CD7tXiZLgNYOE0fiO89wKFnlMQReVTsR8pTZ1jFbLgwDLO/L4l3OeMk2KurUCnps9yF21sEyba/RRiJrTepE97439zvf64LwmTJPN9NPxNtKeUmYvKCW0h3LVY1cbdV3X2ger5FlnziyDhAtsffsDQcK01DhhXdgepD4TvtM+6DGNwnLj7vHDFyoQOq6kf5LViC7RgC/9poagY30DRHFlBLzRlsAjOiahXBiORaizNJzbDEZYYrfWORcHLKMDSXO/aSqPU2WhoJMXKqOrvtdH8GhmUYdR6SzAGr6ZfZ28nq+M7hBwBsosm7ybag9SY7t+Il/1QhKCYNzBTYg/33WHnUhC/DSpuhEfjKkJIn8tromHHZD3PpamnxDTxZXtRPimY3ar+xQrAWoCybkvk542jdeV5WlReZR/JXujXpb9TRLdheQF38EqtLiqBCSwDTccLwwjZfmyrOgSiZJ/lGce2cY=
